/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.defence_system;

/**
 *
 * @author Admin
 */

 class Helicopter extends javax.swing.JFrame implements DefenceObserver {
    private DefenceObservable defenceObservable;
   
    private int position;
   
    
    public Helicopter( ) {
        initComponents();
        setVisible(true);
        btnShoot.setEnabled(false);
        btnMissileOperation.setEnabled(false);
        btnTomaHawk.setEnabled(false);
        setLocationRelativeTo(this);
        setTitle("Helicopter");
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider3 = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        checkBoxPosition = new javax.swing.JCheckBox();
        btnShoot = new javax.swing.JButton();
        btnMissileOperation = new javax.swing.JButton();
        btnTomaHawk = new javax.swing.JButton();
        LableAreaCleared = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(102, 102, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jSlider3.setMajorTickSpacing(20);
        jSlider3.setMinorTickSpacing(20);
        jSlider3.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider3.setPaintLabels(true);
        jSlider3.setPaintTicks(true);
        jSlider3.setSnapToTicks(true);
        jSlider3.setFocusCycleRoot(true);
        jSlider3.setFocusTraversalPolicyProvider(true);
        jSlider3.setInheritsPopupMenu(true);
        jSlider3.setValueIsAdjusting(true);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        checkBoxPosition.setText("Position");
        checkBoxPosition.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkBoxPositionItemStateChanged(evt);
            }
        });
        checkBoxPosition.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                checkBoxPositionAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                checkBoxPositionAncestorRemoved(evt);
            }
        });
        checkBoxPosition.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkBoxPositionStateChanged(evt);
            }
        });
        checkBoxPosition.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                checkBoxPositionFocusGained(evt);
            }
        });
        checkBoxPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxPositionActionPerformed(evt);
            }
        });
        checkBoxPosition.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                checkBoxPositionKeyPressed(evt);
            }
        });

        btnShoot.setText("Shoot");

        btnMissileOperation.setText("Missile Operation");

        btnTomaHawk.setText("Laser Operation");

        LableAreaCleared.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LableAreaCleared.setText("Area Not Cleared");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTextField2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSend))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnTomaHawk, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(checkBoxPosition))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnShoot, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnMissileOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 56, Short.MAX_VALUE)))))
                        .addGap(64, 64, 64)))
                .addGap(34, 34, 34)
                .addComponent(jSlider3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LableAreaCleared, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LableAreaCleared, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnShoot, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMissileOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTomaHawk, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkBoxPosition))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSend))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkBoxPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxPositionActionPerformed
       // btnShoot.setEnabled(true);
         
        // TODO add your handling code here:
        
    }//GEN-LAST:event_checkBoxPositionActionPerformed

    private void checkBoxPositionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkBoxPositionStateChanged
       //  btnShoot.setEnabled(true);
// TODO add your handling code here:
    }//GEN-LAST:event_checkBoxPositionStateChanged

    private void checkBoxPositionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_checkBoxPositionKeyPressed
            // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxPositionKeyPressed

    private void checkBoxPositionAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_checkBoxPositionAncestorAdded
            // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxPositionAncestorAdded

    private void checkBoxPositionAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_checkBoxPositionAncestorRemoved
            // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxPositionAncestorRemoved

    private void checkBoxPositionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_checkBoxPositionFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxPositionFocusGained

    private void checkBoxPositionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkBoxPositionItemStateChanged
      //  checkBoxPosition.setEnabled(true); // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxPositionItemStateChanged

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        
            // TODO add your handling code here:
    }//GEN-LAST:event_btnSendActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LableAreaCleared;
    private javax.swing.JButton btnMissileOperation;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnShoot;
    private javax.swing.JButton btnTomaHawk;
    private javax.swing.JCheckBox checkBoxPosition;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
    
     public void getMessageMain(String Message){
         
     }

    @Override
    public void areaClearLable(boolean clearStatus) {
        if(clearStatus){
            LableAreaCleared.setText("Area Cleared");
        }
        else{
            LableAreaCleared.setText("Area Not  Cleared");
            
        }
    }

    @Override
    public void update(int position) {
        if(checkBoxPosition.isSelected()){
            
          
            if(position>20){
                btnShoot.setEnabled(true);
            }
            else if(position>40){
                btnShoot.setEnabled(true);
                btnMissileOperation.setEnabled(true);
                
                        
            }
            
            else if(position>60){
                 btnShoot.setEnabled(true);
                btnMissileOperation.setEnabled(true);
                btnTomaHawk.setEnabled(true);
            }
            
           
            
            
    
        }
    }
    
    @Override
    public void updateButtons() {
        
            
        }
    }
 
   


