/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.defence_system;

/**
 *
 * @author Admin
 */

 class Submarine extends javax.swing.JFrame implements  DefenceObserver{
    private DefenceObservable defenceObservable;
    private int position;

    
    /**
     * Creates new form Submarine
     */
    public Submarine( ) {
       
        setVisible(true);
        setTitle("Submarine");
        setLocationRelativeTo(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        lableAreaNotCleared = new javax.swing.JLabel();
        btnSubmarineTomahawkMissile = new javax.swing.JButton();
        btnSubmarineSonarOperation = new javax.swing.JButton();
        btnSubmarineShoot = new javax.swing.JButton();
        bbtnTrident2Missile = new javax.swing.JButton();
        jSlider2 = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtrAreaSubmarine = new javax.swing.JTextArea();
        txtSendSubmarine = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jSlider3 = new javax.swing.JSlider();
        checkBoxSubmarinePosition = new javax.swing.JCheckBox();

        jButton1.setText("jButton1");

        jButton6.setText("jButton6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lableAreaNotCleared.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lableAreaNotCleared.setText("Area Not Cleared");

        btnSubmarineTomahawkMissile.setText("Tomahawk Missile");

        btnSubmarineSonarOperation.setText("Sonar Operation");

        btnSubmarineShoot.setText("Shoot");

        bbtnTrident2Missile.setText("Trident-2-Missile");

        jSlider2.setMajorTickSpacing(20);
        jSlider2.setMinorTickSpacing(100);
        jSlider2.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider2.setPaintLabels(true);
        jSlider2.setPaintTicks(true);
        jSlider2.setSnapToTicks(true);
        jSlider2.setFocusTraversalPolicyProvider(true);
        jSlider2.setInheritsPopupMenu(true);
        jSlider2.setOpaque(true);

        jLabel2.setText("Energy");

        jLabel3.setText("Oxygen");

        txtrAreaSubmarine.setColumns(20);
        txtrAreaSubmarine.setRows(5);
        jScrollPane1.setViewportView(txtrAreaSubmarine);

        txtSendSubmarine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSendSubmarineActionPerformed(evt);
            }
        });

        jButton7.setText("Send");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jSlider3.setMajorTickSpacing(20);
        jSlider3.setMinorTickSpacing(50);
        jSlider3.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider3.setPaintLabels(true);
        jSlider3.setPaintTicks(true);
        jSlider3.setSnapToTicks(true);
        jSlider3.setValue(100);
        jSlider3.setFocusTraversalPolicyProvider(true);
        jSlider3.setInheritsPopupMenu(true);
        jSlider3.setOpaque(true);

        checkBoxSubmarinePosition.setText("Position");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lableAreaNotCleared, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(291, 291, 291)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnSubmarineTomahawkMissile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSubmarineShoot, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSubmarineSonarOperation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bbtnTrident2Missile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkBoxSubmarinePosition))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSendSubmarine, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7)))
                .addGap(18, 21, Short.MAX_VALUE)
                .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnSubmarineShoot, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSubmarineSonarOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(checkBoxSubmarinePosition)
                                .addGap(14, 14, 14)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSubmarineTomahawkMissile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bbtnTrident2Missile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSendSubmarine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(lableAreaNotCleared, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void txtSendSubmarineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSendSubmarineActionPerformed
        String  txtMessage=txtSendSubmarine.getText();
        defenceObservable.getMessageMain(txtMessage);
                // TODO add your handling code here:
    }//GEN-LAST:event_txtSendSubmarineActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbtnTrident2Missile;
    private javax.swing.JButton btnSubmarineShoot;
    private javax.swing.JButton btnSubmarineSonarOperation;
    private javax.swing.JButton btnSubmarineTomahawkMissile;
    private javax.swing.JCheckBox checkBoxSubmarinePosition;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JLabel lableAreaNotCleared;
    private javax.swing.JTextField txtSendSubmarine;
    private javax.swing.JTextArea txtrAreaSubmarine;
    // End of variables declaration//GEN-END:variables

    @Override
    public void getMessageMain(String message) {
        
        txtrAreaSubmarine.setText(message);
        txtrAreaSubmarine.append(message+"\n");
        
    }
    
    
    
    @Override
    public void areaClearLable(boolean clearStatus) {
        if(clearStatus){
            lableAreaNotCleared.setText("Area Cleared");
        }
        else{
            lableAreaNotCleared.setText("Area Not  Cleared");
            
        }
   }

    @Override
    public void update(int position) {
      this.position=position;
      updateButtons();
      
    }
    
    @Override
    public void updateButtons() {
       if(checkBoxSubmarinePosition.isSelected()){
           if (position>20){
               btnSubmarineShoot.setEnabled(true);
           }
           else if(position>40){
               btnSubmarineSonarOperation.setEnabled(true);
               btnSubmarineSonarOperation.setEnabled(true);
           }
           else if(position>60){
               btnSubmarineTomahawkMissile.setEnabled(true);
               btnSubmarineSonarOperation.setEnabled(true);
               btnSubmarineTomahawkMissile.setEnabled(true);
           }
           else if(position>80){
               btnSubmarineTomahawkMissile.setEnabled(true);
               btnSubmarineSonarOperation.setEnabled(true);
               btnSubmarineTomahawkMissile.setEnabled(true);
               bbtnTrident2Missile.setEnabled(true);
               
               
               
           }
            if (position<20){
                btnSubmarineTomahawkMissile.setEnabled(false);
               btnSubmarineSonarOperation.setEnabled(false);
               btnSubmarineTomahawkMissile.setEnabled(false);
               bbtnTrident2Missile.setEnabled(false);
           }
       }
     }
}
